### ISSUE TITLE
FIPS should always be 5 digits

### ISSUE THREAD

**Issue by patricksheehan** [CovidCountyData/covidcountydata.py#3]
It looks like FIPS codes for counties are returned as integers, some having 4 digits, others having 5

https://www.usna.edu/Users/oceano/pguth/md_help/html/leading_0.htm

Not sure if this is on the client library side or the API itself

**Comment by sglyon** [comment]
Hey @patricksheehan thanks for bringing this up.

we've had mixed feedback about a desire for "true" fips codes with 5-digits and encoded as strings vs the more compat representation as integers.

I think this vote pushes us over the edge to always returning a fips code as 5 digits for a county and 2 digits for a state (padded by leading zeros where necessary).

We need to check with a few of our heavy/long-time users to make sure we don't cause breakages downstream, but we'll get on that ASAP and let you know

**Comment by patricksheehan** [comment]
@sglyon thanks! I agree that the backend implementation (for filtering, etc.) is more convenient (though oddly enough I think a string with 5 characters could have less bytes than an integer!). But yeah from a usability standpoint it's great to have "true" FIPS so we can throw this into mapping visualizations without padding on our end.

Let us know if/when this is changed! Thanks again.

**Comment by sglyon** [comment]
This has now happened as of version 0.5.0!

We decided to make the change in a non-breaking way.

The `location` column will remain as is -- an integer encoded representation of the fips code, with leading zeros trimmed where appropriate.

There is now a new column named `fips` that contains a string that always has 2 characters for a US state and 5 characters for a us county.

Please upgrade (using e.g. `pip install --upgrade covidcountydata`) to access this new column
